# Generated by Django 5.1.3 on 2024-12-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_category_name_rename_title_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciencePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science_persons', to='core.article')),
            ],
        ),
    ]
